%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

warning off
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'mergedModel2';
M_.dynare_version = '4.5.6';
oo_.dynare_version = '4.5.6';
options_.dynare_version = '4.5.6';
%
% Some global variables initialization
%
global_initialization;
diary off;
M_.exo_names = 'Dummy_tax';
M_.exo_names_tex = 'Dummy\_tax';
M_.exo_names_long = 'Dummy_tax';
M_.exo_names = char(M_.exo_names, 'shock0_d');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock0\_d');
M_.exo_names_long = char(M_.exo_names_long, 'shock0_d');
M_.exo_names = char(M_.exo_names, 'shock1_d');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock1\_d');
M_.exo_names_long = char(M_.exo_names_long, 'shock1_d');
M_.exo_names = char(M_.exo_names, 'shockneg0_d');
M_.exo_names_tex = char(M_.exo_names_tex, 'shockneg0\_d');
M_.exo_names_long = char(M_.exo_names_long, 'shockneg0_d');
M_.exo_names = char(M_.exo_names, 'shockneg1_d');
M_.exo_names_tex = char(M_.exo_names_tex, 'shockneg1\_d');
M_.exo_names_long = char(M_.exo_names_long, 'shockneg1_d');
M_.exo_names = char(M_.exo_names, 'shock0_grants');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock0\_grants');
M_.exo_names_long = char(M_.exo_names_long, 'shock0_grants');
M_.exo_names = char(M_.exo_names, 'shock1_grants');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock1\_grants');
M_.exo_names_long = char(M_.exo_names_long, 'shock1_grants');
M_.exo_names = char(M_.exo_names, 'shockneg0_grants');
M_.exo_names_tex = char(M_.exo_names_tex, 'shockneg0\_grants');
M_.exo_names_long = char(M_.exo_names_long, 'shockneg0_grants');
M_.exo_names = char(M_.exo_names, 'shockneg1_grants');
M_.exo_names_tex = char(M_.exo_names_tex, 'shockneg1\_grants');
M_.exo_names_long = char(M_.exo_names_long, 'shockneg1_grants');
M_.exo_names = char(M_.exo_names, 'shock0_remit');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock0\_remit');
M_.exo_names_long = char(M_.exo_names_long, 'shock0_remit');
M_.exo_names = char(M_.exo_names, 'shockneg0_remit');
M_.exo_names_tex = char(M_.exo_names_tex, 'shockneg0\_remit');
M_.exo_names_long = char(M_.exo_names_long, 'shockneg0_remit');
M_.exo_names = char(M_.exo_names, 'shockneg1_remit');
M_.exo_names_tex = char(M_.exo_names_tex, 'shockneg1\_remit');
M_.exo_names_long = char(M_.exo_names_long, 'shockneg1_remit');
M_.exo_names = char(M_.exo_names, 'shock0_oilr');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock0\_oilr');
M_.exo_names_long = char(M_.exo_names_long, 'shock0_oilr');
M_.exo_names = char(M_.exo_names, 'shock1_oilr');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock1\_oilr');
M_.exo_names_long = char(M_.exo_names_long, 'shock1_oilr');
M_.exo_names = char(M_.exo_names, 'shockneg0_oilr');
M_.exo_names_tex = char(M_.exo_names_tex, 'shockneg0\_oilr');
M_.exo_names_long = char(M_.exo_names_long, 'shockneg0_oilr');
M_.exo_names = char(M_.exo_names, 'shockneg1_oilr');
M_.exo_names_tex = char(M_.exo_names_tex, 'shockneg1\_oilr');
M_.exo_names_long = char(M_.exo_names_long, 'shockneg1_oilr');
M_.exo_names = char(M_.exo_names, 'shock0_hbar');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock0\_hbar');
M_.exo_names_long = char(M_.exo_names_long, 'shock0_hbar');
M_.exo_names = char(M_.exo_names, 'shock0_hlbar');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock0\_hlbar');
M_.exo_names_long = char(M_.exo_names_long, 'shock0_hlbar');
M_.exo_names = char(M_.exo_names, 'shock0_Tbar');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock0\_Tbar');
M_.exo_names_long = char(M_.exo_names_long, 'shock0_Tbar');
M_.exo_names = char(M_.exo_names, 'shock0_px');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock0\_px');
M_.exo_names_long = char(M_.exo_names_long, 'shock0_px');
M_.exo_names = char(M_.exo_names, 'shock1_px');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock1\_px');
M_.exo_names_long = char(M_.exo_names_long, 'shock1_px');
M_.exo_names = char(M_.exo_names, 'shockneg0_px');
M_.exo_names_tex = char(M_.exo_names_tex, 'shockneg0\_px');
M_.exo_names_long = char(M_.exo_names_long, 'shockneg0_px');
M_.exo_names = char(M_.exo_names, 'shockneg1_px');
M_.exo_names_tex = char(M_.exo_names_tex, 'shockneg1\_px');
M_.exo_names_long = char(M_.exo_names_long, 'shockneg1_px');
M_.exo_names = char(M_.exo_names, 'shock0_pm');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock0\_pm');
M_.exo_names_long = char(M_.exo_names_long, 'shock0_pm');
M_.exo_names = char(M_.exo_names, 'shock1_pm');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock1\_pm');
M_.exo_names_long = char(M_.exo_names_long, 'shock1_pm');
M_.exo_names = char(M_.exo_names, 'shockneg0_pm');
M_.exo_names_tex = char(M_.exo_names_tex, 'shockneg0\_pm');
M_.exo_names_long = char(M_.exo_names_long, 'shockneg0_pm');
M_.exo_names = char(M_.exo_names, 'shockneg1_pm');
M_.exo_names_tex = char(M_.exo_names_tex, 'shockneg1\_pm');
M_.exo_names_long = char(M_.exo_names_long, 'shockneg1_pm');
M_.exo_names = char(M_.exo_names, 'shock0_pmm');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock0\_pmm');
M_.exo_names_long = char(M_.exo_names_long, 'shock0_pmm');
M_.exo_names = char(M_.exo_names, 'shock1_pmm');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock1\_pmm');
M_.exo_names_long = char(M_.exo_names_long, 'shock1_pmm');
M_.exo_names = char(M_.exo_names, 'shockneg0_pmm');
M_.exo_names_tex = char(M_.exo_names_tex, 'shockneg0\_pmm');
M_.exo_names_long = char(M_.exo_names_long, 'shockneg0_pmm');
M_.exo_names = char(M_.exo_names, 'shockneg1_pmm');
M_.exo_names_tex = char(M_.exo_names_tex, 'shockneg1\_pmm');
M_.exo_names_long = char(M_.exo_names_long, 'shockneg1_pmm');
M_.exo_names = char(M_.exo_names, 'dc_target');
M_.exo_names_tex = char(M_.exo_names_tex, 'dc\_target');
M_.exo_names_long = char(M_.exo_names_long, 'dc_target');
M_.exo_names = char(M_.exo_names, 'int_repayment0');
M_.exo_names_tex = char(M_.exo_names_tex, 'int\_repayment0');
M_.exo_names_long = char(M_.exo_names_long, 'int_repayment0');
M_.exo_names = char(M_.exo_names, 'int_repayment1');
M_.exo_names_tex = char(M_.exo_names_tex, 'int\_repayment1');
M_.exo_names_long = char(M_.exo_names_long, 'int_repayment1');
M_.exo_names = char(M_.exo_names, 'shocknd_kx');
M_.exo_names_tex = char(M_.exo_names_tex, 'shocknd\_kx');
M_.exo_names_long = char(M_.exo_names_long, 'shocknd_kx');
M_.exo_names = char(M_.exo_names, 'shocknd_kn');
M_.exo_names_tex = char(M_.exo_names_tex, 'shocknd\_kn');
M_.exo_names_long = char(M_.exo_names_long, 'shocknd_kn');
M_.exo_names = char(M_.exo_names, 'shocknd_z');
M_.exo_names_tex = char(M_.exo_names_tex, 'shocknd\_z');
M_.exo_names_long = char(M_.exo_names_long, 'shocknd_z');
M_.exo_names = char(M_.exo_names, 'shocknd_grantsizi');
M_.exo_names_tex = char(M_.exo_names_tex, 'shocknd\_grantsizi');
M_.exo_names_long = char(M_.exo_names_long, 'shocknd_grantsizi');
M_.exo_names = char(M_.exo_names, 'shocknd_grantsiza');
M_.exo_names_tex = char(M_.exo_names_tex, 'shocknd\_grantsiza');
M_.exo_names_long = char(M_.exo_names_long, 'shocknd_grantsiza');
M_.exo_names = char(M_.exo_names, 'shock0_izi');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock0\_izi');
M_.exo_names_long = char(M_.exo_names_long, 'shock0_izi');
M_.exo_names = char(M_.exo_names, 'shock1_izi');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock1\_izi');
M_.exo_names_long = char(M_.exo_names_long, 'shock1_izi');
M_.exo_names = char(M_.exo_names, 'shockneg0_izi');
M_.exo_names_tex = char(M_.exo_names_tex, 'shockneg0\_izi');
M_.exo_names_long = char(M_.exo_names_long, 'shockneg0_izi');
M_.exo_names = char(M_.exo_names, 'shockneg1_izi');
M_.exo_names_tex = char(M_.exo_names_tex, 'shockneg1\_izi');
M_.exo_names_long = char(M_.exo_names_long, 'shockneg1_izi');
M_.exo_names = char(M_.exo_names, 'shock0_iza');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock0\_iza');
M_.exo_names_long = char(M_.exo_names_long, 'shock0_iza');
M_.exo_names = char(M_.exo_names, 'shock1_iza');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock1\_iza');
M_.exo_names_long = char(M_.exo_names_long, 'shock1_iza');
M_.exo_names = char(M_.exo_names, 'shockneg0_iza');
M_.exo_names_tex = char(M_.exo_names_tex, 'shockneg0\_iza');
M_.exo_names_long = char(M_.exo_names_long, 'shockneg0_iza');
M_.exo_names = char(M_.exo_names, 'shockneg1_iza');
M_.exo_names_tex = char(M_.exo_names_tex, 'shockneg1\_iza');
M_.exo_names_long = char(M_.exo_names_long, 'shockneg1_iza');
M_.exo_names = char(M_.exo_names, 'shocknd_rextg');
M_.exo_names_tex = char(M_.exo_names_tex, 'shocknd\_rextg');
M_.exo_names_long = char(M_.exo_names_long, 'shocknd_rextg');
M_.exo_names = char(M_.exo_names, 'shocknd_sav');
M_.exo_names_tex = char(M_.exo_names_tex, 'shocknd\_sav');
M_.exo_names_long = char(M_.exo_names_long, 'shocknd_sav');
M_.exo_names = char(M_.exo_names, 'shocknd_izi');
M_.exo_names_tex = char(M_.exo_names_tex, 'shocknd\_izi');
M_.exo_names_long = char(M_.exo_names_long, 'shocknd_izi');
M_.exo_names = char(M_.exo_names, 'shocknd_yn');
M_.exo_names_tex = char(M_.exo_names_tex, 'shocknd\_yn');
M_.exo_names_long = char(M_.exo_names_long, 'shocknd_yn');
M_.exo_names = char(M_.exo_names, 'shocknd_yx');
M_.exo_names_tex = char(M_.exo_names_tex, 'shocknd\_yx');
M_.exo_names_long = char(M_.exo_names_long, 'shocknd_yx');
M_.exo_names = char(M_.exo_names, 'sh_timeline');
M_.exo_names_tex = char(M_.exo_names_tex, 'sh\_timeline');
M_.exo_names_long = char(M_.exo_names_long, 'sh_timeline');
M_.exo_names = char(M_.exo_names, 'shocknd_s');
M_.exo_names_tex = char(M_.exo_names_tex, 'shocknd\_s');
M_.exo_names_long = char(M_.exo_names_long, 'shocknd_s');
M_.exo_names = char(M_.exo_names, 'shocknd_ax');
M_.exo_names_tex = char(M_.exo_names_tex, 'shocknd\_ax');
M_.exo_names_long = char(M_.exo_names_long, 'shocknd_ax');
M_.exo_names = char(M_.exo_names, 'shocknd_an');
M_.exo_names_tex = char(M_.exo_names_tex, 'shocknd\_an');
M_.exo_names_long = char(M_.exo_names_long, 'shocknd_an');
M_.exo_names = char(M_.exo_names, 'y_target');
M_.exo_names_tex = char(M_.exo_names_tex, 'y\_target');
M_.exo_names_long = char(M_.exo_names_long, 'y_target');
M_.exo_names = char(M_.exo_names, 'shock_s');
M_.exo_names_tex = char(M_.exo_names_tex, 'shock\_s');
M_.exo_names_long = char(M_.exo_names_long, 'shock_s');
M_.endo_names = 'qx';
M_.endo_names_tex = 'qx';
M_.endo_names_long = 'qx';
M_.endo_names = char(M_.endo_names, 'qn');
M_.endo_names_tex = char(M_.endo_names_tex, 'qn');
M_.endo_names_long = char(M_.endo_names_long, 'qn');
M_.endo_names = char(M_.endo_names, 'ynom');
M_.endo_names_tex = char(M_.endo_names_tex, 'ynom');
M_.endo_names_long = char(M_.endo_names_long, 'ynom');
M_.endo_names = char(M_.endo_names, 'growth_plot');
M_.endo_names_tex = char(M_.endo_names_tex, 'growth\_plot');
M_.endo_names_long = char(M_.endo_names_long, 'growth_plot');
M_.endo_names = char(M_.endo_names, 'kx');
M_.endo_names_tex = char(M_.endo_names_tex, 'kx');
M_.endo_names_long = char(M_.endo_names_long, 'kx');
M_.endo_names = char(M_.endo_names, 'kn');
M_.endo_names_tex = char(M_.endo_names_tex, 'kn');
M_.endo_names_long = char(M_.endo_names_long, 'kn');
M_.endo_names = char(M_.endo_names, 'L_x');
M_.endo_names_tex = char(M_.endo_names_tex, 'L\_x');
M_.endo_names_long = char(M_.endo_names_long, 'L_x');
M_.endo_names = char(M_.endo_names, 'L_n');
M_.endo_names_tex = char(M_.endo_names_tex, 'L\_n');
M_.endo_names_long = char(M_.endo_names_long, 'L_n');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, 'L');
M_.endo_names_long = char(M_.endo_names_long, 'L');
M_.endo_names = char(M_.endo_names, 'Lh');
M_.endo_names_tex = char(M_.endo_names_tex, 'Lh');
M_.endo_names_long = char(M_.endo_names_long, 'Lh');
M_.endo_names = char(M_.endo_names, 'ix');
M_.endo_names_tex = char(M_.endo_names_tex, 'ix');
M_.endo_names_long = char(M_.endo_names_long, 'ix');
M_.endo_names = char(M_.endo_names, 'in');
M_.endo_names_tex = char(M_.endo_names_tex, 'in');
M_.endo_names_long = char(M_.endo_names_long, 'in');
M_.endo_names = char(M_.endo_names, 'rx');
M_.endo_names_tex = char(M_.endo_names_tex, 'rx');
M_.endo_names_long = char(M_.endo_names_long, 'rx');
M_.endo_names = char(M_.endo_names, 'rn');
M_.endo_names_tex = char(M_.endo_names_tex, 'rn');
M_.endo_names_long = char(M_.endo_names_long, 'rn');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, 'w');
M_.endo_names_long = char(M_.endo_names_long, 'w');
M_.endo_names = char(M_.endo_names, 'pk');
M_.endo_names_tex = char(M_.endo_names_tex, 'pk');
M_.endo_names_long = char(M_.endo_names_long, 'pk');
M_.endo_names = char(M_.endo_names, 'pz');
M_.endo_names_tex = char(M_.endo_names_tex, 'pz');
M_.endo_names_long = char(M_.endo_names_long, 'pz');
M_.endo_names = char(M_.endo_names, 'pn');
M_.endo_names_tex = char(M_.endo_names_tex, 'pn');
M_.endo_names_long = char(M_.endo_names_long, 'pn');
M_.endo_names = char(M_.endo_names, 'p');
M_.endo_names_tex = char(M_.endo_names_tex, 'p');
M_.endo_names_long = char(M_.endo_names_long, 'p');
M_.endo_names = char(M_.endo_names, 'h');
M_.endo_names_tex = char(M_.endo_names_tex, 'h');
M_.endo_names_long = char(M_.endo_names_long, 'h');
M_.endo_names = char(M_.endo_names, 'T');
M_.endo_names_tex = char(M_.endo_names_tex, 'T');
M_.endo_names_long = char(M_.endo_names_long, 'T');
M_.endo_names = char(M_.endo_names, 'hl');
M_.endo_names_tex = char(M_.endo_names_tex, 'hl');
M_.endo_names_long = char(M_.endo_names_long, 'hl');
M_.endo_names = char(M_.endo_names, 'GAP');
M_.endo_names_tex = char(M_.endo_names_tex, 'GAP');
M_.endo_names_long = char(M_.endo_names_long, 'GAP');
M_.endo_names = char(M_.endo_names, 'bstar');
M_.endo_names_tex = char(M_.endo_names_tex, 'bstar');
M_.endo_names_long = char(M_.endo_names_long, 'bstar');
M_.endo_names = char(M_.endo_names, 'b');
M_.endo_names_tex = char(M_.endo_names_tex, 'b');
M_.endo_names_long = char(M_.endo_names_long, 'b');
M_.endo_names = char(M_.endo_names, 'dc');
M_.endo_names_tex = char(M_.endo_names_tex, 'dc');
M_.endo_names_long = char(M_.endo_names_long, 'dc');
M_.endo_names = char(M_.endo_names, 'd');
M_.endo_names_tex = char(M_.endo_names_tex, 'd');
M_.endo_names_long = char(M_.endo_names_long, 'd');
M_.endo_names = char(M_.endo_names, 'dplot');
M_.endo_names_tex = char(M_.endo_names_tex, 'dplot');
M_.endo_names_long = char(M_.endo_names_long, 'dplot');
M_.endo_names = char(M_.endo_names, 'netbwconc');
M_.endo_names_tex = char(M_.endo_names_tex, 'netbwconc');
M_.endo_names_long = char(M_.endo_names_long, 'netbwconc');
M_.endo_names = char(M_.endo_names, 'e');
M_.endo_names_tex = char(M_.endo_names_tex, 'e');
M_.endo_names_long = char(M_.endo_names_long, 'e');
M_.endo_names = char(M_.endo_names, 'eh');
M_.endo_names_tex = char(M_.endo_names_tex, 'eh');
M_.endo_names_long = char(M_.endo_names_long, 'eh');
M_.endo_names = char(M_.endo_names, 'r');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'r');
M_.endo_names = char(M_.endo_names, 'r_d');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_d');
M_.endo_names_long = char(M_.endo_names_long, 'r_d');
M_.endo_names = char(M_.endo_names, 'rext');
M_.endo_names_tex = char(M_.endo_names_tex, 'rext');
M_.endo_names_long = char(M_.endo_names_long, 'rext');
M_.endo_names = char(M_.endo_names, 'rextg');
M_.endo_names_tex = char(M_.endo_names_tex, 'rextg');
M_.endo_names_long = char(M_.endo_names_long, 'rextg');
M_.endo_names = char(M_.endo_names, 'grants');
M_.endo_names_tex = char(M_.endo_names_tex, 'grants');
M_.endo_names_long = char(M_.endo_names_long, 'grants');
M_.endo_names = char(M_.endo_names, 'remit');
M_.endo_names_tex = char(M_.endo_names_tex, 'remit');
M_.endo_names_long = char(M_.endo_names_long, 'remit');
M_.endo_names = char(M_.endo_names, 'oilr');
M_.endo_names_tex = char(M_.endo_names_tex, 'oilr');
M_.endo_names_long = char(M_.endo_names_long, 'oilr');
M_.endo_names = char(M_.endo_names, 'tot');
M_.endo_names_tex = char(M_.endo_names_tex, 'tot');
M_.endo_names_long = char(M_.endo_names_long, 'tot');
M_.endo_names = char(M_.endo_names, 'totmm');
M_.endo_names_tex = char(M_.endo_names_tex, 'totmm');
M_.endo_names_long = char(M_.endo_names_long, 'totmm');
M_.endo_names = char(M_.endo_names, 'rer');
M_.endo_names_tex = char(M_.endo_names_tex, 'rer');
M_.endo_names_long = char(M_.endo_names_long, 'rer');
M_.endo_names = char(M_.endo_names, 'px');
M_.endo_names_tex = char(M_.endo_names_tex, 'px');
M_.endo_names_long = char(M_.endo_names_long, 'px');
M_.endo_names = char(M_.endo_names, 'pm');
M_.endo_names_tex = char(M_.endo_names_tex, 'pm');
M_.endo_names_long = char(M_.endo_names_long, 'pm');
M_.endo_names = char(M_.endo_names, 'pmm');
M_.endo_names_tex = char(M_.endo_names_tex, 'pmm');
M_.endo_names_long = char(M_.endo_names_long, 'pmm');
M_.endo_names = char(M_.endo_names, 'a_x');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_x');
M_.endo_names_long = char(M_.endo_names_long, 'a_x');
M_.endo_names = char(M_.endo_names, 'a_n');
M_.endo_names_tex = char(M_.endo_names_tex, 'a\_n');
M_.endo_names_long = char(M_.endo_names_long, 'a_n');
M_.endo_names = char(M_.endo_names, 'zi');
M_.endo_names_tex = char(M_.endo_names_tex, 'zi');
M_.endo_names_long = char(M_.endo_names_long, 'zi');
M_.endo_names = char(M_.endo_names, 'zie');
M_.endo_names_tex = char(M_.endo_names_tex, 'zie');
M_.endo_names_long = char(M_.endo_names_long, 'zie');
M_.endo_names = char(M_.endo_names, 'za');
M_.endo_names_tex = char(M_.endo_names_tex, 'za');
M_.endo_names_long = char(M_.endo_names_long, 'za');
M_.endo_names = char(M_.endo_names, 'zae');
M_.endo_names_tex = char(M_.endo_names_tex, 'zae');
M_.endo_names_long = char(M_.endo_names_long, 'zae');
M_.endo_names = char(M_.endo_names, 'izi');
M_.endo_names_tex = char(M_.endo_names_tex, 'izi');
M_.endo_names_long = char(M_.endo_names_long, 'izi');
M_.endo_names = char(M_.endo_names, 'iza');
M_.endo_names_tex = char(M_.endo_names_tex, 'iza');
M_.endo_names_long = char(M_.endo_names_long, 'iza');
M_.endo_names = char(M_.endo_names, 'Rzi');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rzi');
M_.endo_names_long = char(M_.endo_names_long, 'Rzi');
M_.endo_names = char(M_.endo_names, 'Rza');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rza');
M_.endo_names_long = char(M_.endo_names_long, 'Rza');
M_.endo_names = char(M_.endo_names, 'Sav');
M_.endo_names_tex = char(M_.endo_names_tex, 'Sav');
M_.endo_names_long = char(M_.endo_names_long, 'Sav');
M_.endo_names = char(M_.endo_names, 'zte');
M_.endo_names_tex = char(M_.endo_names_tex, 'zte');
M_.endo_names_long = char(M_.endo_names_long, 'zte');
M_.endo_names = char(M_.endo_names, 'Rzt');
M_.endo_names_tex = char(M_.endo_names_tex, 'Rzt');
M_.endo_names_long = char(M_.endo_names_long, 'Rzt');
M_.endo_names = char(M_.endo_names, 's');
M_.endo_names_tex = char(M_.endo_names_tex, 's');
M_.endo_names_long = char(M_.endo_names_long, 's');
M_.endo_names = char(M_.endo_names, 'yreal');
M_.endo_names_tex = char(M_.endo_names_tex, 'yreal');
M_.endo_names_long = char(M_.endo_names_long, 'yreal');
M_.endo_names = char(M_.endo_names, 'tfp_adj');
M_.endo_names_tex = char(M_.endo_names_tex, 'tfp\_adj');
M_.endo_names_long = char(M_.endo_names_long, 'tfp_adj');
M_.endo_partitions = struct();
M_.param_names = 'beta';
M_.param_names_tex = 'beta';
M_.param_names_long = 'beta';
M_.param_names = char(M_.param_names, 'beta_t');
M_.param_names_tex = char(M_.param_names_tex, 'beta\_t');
M_.param_names_long = char(M_.param_names_long, 'beta_t');
M_.param_names = char(M_.param_names, 'delta_x');
M_.param_names_tex = char(M_.param_names_tex, 'delta\_x');
M_.param_names_long = char(M_.param_names_long, 'delta_x');
M_.param_names = char(M_.param_names, 'delta_n');
M_.param_names_tex = char(M_.param_names_tex, 'delta\_n');
M_.param_names_long = char(M_.param_names_long, 'delta_n');
M_.param_names = char(M_.param_names, 'delta_zi');
M_.param_names_tex = char(M_.param_names_tex, 'delta\_zi');
M_.param_names_long = char(M_.param_names_long, 'delta_zi');
M_.param_names = char(M_.param_names, 'delta_za');
M_.param_names_tex = char(M_.param_names_tex, 'delta\_za');
M_.param_names_long = char(M_.param_names_long, 'delta_za');
M_.param_names = char(M_.param_names, 'alpha_k');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_k');
M_.param_names_long = char(M_.param_names_long, 'alpha_k');
M_.param_names = char(M_.param_names, 'alpha_z');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_z');
M_.param_names_long = char(M_.param_names_long, 'alpha_z');
M_.param_names = char(M_.param_names, 'alpha_x');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_x');
M_.param_names_long = char(M_.param_names_long, 'alpha_x');
M_.param_names = char(M_.param_names, 'alpha_n');
M_.param_names_tex = char(M_.param_names_tex, 'alpha\_n');
M_.param_names_long = char(M_.param_names_long, 'alpha_n');
M_.param_names = char(M_.param_names, 'a_k');
M_.param_names_tex = char(M_.param_names_tex, 'a\_k');
M_.param_names_long = char(M_.param_names_long, 'a_k');
M_.param_names = char(M_.param_names, 'a_z');
M_.param_names_tex = char(M_.param_names_tex, 'a\_z');
M_.param_names_long = char(M_.param_names_long, 'a_z');
M_.param_names = char(M_.param_names, 'a_no');
M_.param_names_tex = char(M_.param_names_tex, 'a\_no');
M_.param_names_long = char(M_.param_names_long, 'a_no');
M_.param_names = char(M_.param_names, 'a_xo');
M_.param_names_tex = char(M_.param_names_tex, 'a\_xo');
M_.param_names_long = char(M_.param_names_long, 'a_xo');
M_.param_names = char(M_.param_names, 'psi_x');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_x');
M_.param_names_long = char(M_.param_names_long, 'psi_x');
M_.param_names = char(M_.param_names, 'psi_n');
M_.param_names_tex = char(M_.param_names_tex, 'psi\_n');
M_.param_names_long = char(M_.param_names_long, 'psi_n');
M_.param_names = char(M_.param_names, 'xi_x');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_x');
M_.param_names_long = char(M_.param_names_long, 'xi_x');
M_.param_names = char(M_.param_names, 'xi_n');
M_.param_names_tex = char(M_.param_names_tex, 'xi\_n');
M_.param_names_long = char(M_.param_names_long, 'xi_n');
M_.param_names = char(M_.param_names, 'sigmah');
M_.param_names_tex = char(M_.param_names_tex, 'sigmah');
M_.param_names_long = char(M_.param_names_long, 'sigmah');
M_.param_names = char(M_.param_names, 'phhi');
M_.param_names_tex = char(M_.param_names_tex, 'phhi');
M_.param_names_long = char(M_.param_names_long, 'phhi');
M_.param_names = char(M_.param_names, 'kappah');
M_.param_names_tex = char(M_.param_names_tex, 'kappah');
M_.param_names_long = char(M_.param_names_long, 'kappah');
M_.param_names = char(M_.param_names, 'nu_x');
M_.param_names_tex = char(M_.param_names_tex, 'nu\_x');
M_.param_names_long = char(M_.param_names_long, 'nu_x');
M_.param_names = char(M_.param_names, 'nu_n');
M_.param_names_tex = char(M_.param_names_tex, 'nu\_n');
M_.param_names_long = char(M_.param_names_long, 'nu_n');
M_.param_names = char(M_.param_names, 'sigma_x');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_x');
M_.param_names_long = char(M_.param_names_long, 'sigma_x');
M_.param_names = char(M_.param_names, 'sigma_n');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_n');
M_.param_names_long = char(M_.param_names_long, 'sigma_n');
M_.param_names = char(M_.param_names, 'gama_n');
M_.param_names_tex = char(M_.param_names_tex, 'gama\_n');
M_.param_names_long = char(M_.param_names_long, 'gama_n');
M_.param_names = char(M_.param_names, 'gama_x');
M_.param_names_tex = char(M_.param_names_tex, 'gama\_x');
M_.param_names_long = char(M_.param_names_long, 'gama_x');
M_.param_names = char(M_.param_names, 'gama_m');
M_.param_names_tex = char(M_.param_names_tex, 'gama\_m');
M_.param_names_long = char(M_.param_names_long, 'gama_m');
M_.param_names = char(M_.param_names, 'rho_x');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_x');
M_.param_names_long = char(M_.param_names_long, 'rho_x');
M_.param_names = char(M_.param_names, 'rho_m');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_m');
M_.param_names_long = char(M_.param_names_long, 'rho_m');
M_.param_names = char(M_.param_names, 'tau');
M_.param_names_tex = char(M_.param_names_tex, 'tau');
M_.param_names_long = char(M_.param_names_long, 'tau');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'g');
M_.param_names_tex = char(M_.param_names_tex, 'g');
M_.param_names_long = char(M_.param_names_long, 'g');
M_.param_names = char(M_.param_names, 'epsilon');
M_.param_names_tex = char(M_.param_names_tex, 'epsilon');
M_.param_names_long = char(M_.param_names_long, 'epsilon');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, 'phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'miu');
M_.param_names_tex = char(M_.param_names_tex, 'miu');
M_.param_names_long = char(M_.param_names_long, 'miu');
M_.param_names = char(M_.param_names, 's_o');
M_.param_names_tex = char(M_.param_names_tex, 's\_o');
M_.param_names_long = char(M_.param_names_long, 's_o');
M_.param_names = char(M_.param_names, 's_s');
M_.param_names_tex = char(M_.param_names_tex, 's\_s');
M_.param_names_long = char(M_.param_names_long, 's_s');
M_.param_names = char(M_.param_names, 'rstar');
M_.param_names_tex = char(M_.param_names_tex, 'rstar');
M_.param_names_long = char(M_.param_names_long, 'rstar');
M_.param_names = char(M_.param_names, 'nu');
M_.param_names_tex = char(M_.param_names_tex, 'nu');
M_.param_names_long = char(M_.param_names_long, 'nu');
M_.param_names = char(M_.param_names, 'etag');
M_.param_names_tex = char(M_.param_names_tex, 'etag');
M_.param_names_long = char(M_.param_names_long, 'etag');
M_.param_names = char(M_.param_names, 'nug');
M_.param_names_tex = char(M_.param_names_tex, 'nug');
M_.param_names_long = char(M_.param_names_long, 'nug');
M_.param_names = char(M_.param_names, 'a_ratio');
M_.param_names_tex = char(M_.param_names_tex, 'a\_ratio');
M_.param_names_long = char(M_.param_names_long, 'a_ratio');
M_.param_names = char(M_.param_names, 'VA_n');
M_.param_names_tex = char(M_.param_names_tex, 'VA\_n');
M_.param_names_long = char(M_.param_names_long, 'VA_n');
M_.param_names = char(M_.param_names, 'share_bstar');
M_.param_names_tex = char(M_.param_names_tex, 'share\_bstar');
M_.param_names_long = char(M_.param_names_long, 'share_bstar');
M_.param_names = char(M_.param_names, 'share_b');
M_.param_names_tex = char(M_.param_names_tex, 'share\_b');
M_.param_names_long = char(M_.param_names_long, 'share_b');
M_.param_names = char(M_.param_names, 'share_d');
M_.param_names_tex = char(M_.param_names_tex, 'share\_d');
M_.param_names_long = char(M_.param_names_long, 'share_d');
M_.param_names = char(M_.param_names, 'lambda');
M_.param_names_tex = char(M_.param_names_tex, 'lambda');
M_.param_names_long = char(M_.param_names_long, 'lambda');
M_.param_names = char(M_.param_names, 'lambda_h');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_h');
M_.param_names_long = char(M_.param_names_long, 'lambda_h');
M_.param_names = char(M_.param_names, 'lambda_hl');
M_.param_names_tex = char(M_.param_names_tex, 'lambda\_hl');
M_.param_names_long = char(M_.param_names_long, 'lambda_hl');
M_.param_names = char(M_.param_names, 'lambda1');
M_.param_names_tex = char(M_.param_names_tex, 'lambda1');
M_.param_names_long = char(M_.param_names_long, 'lambda1');
M_.param_names = char(M_.param_names, 'lambda2');
M_.param_names_tex = char(M_.param_names_tex, 'lambda2');
M_.param_names_long = char(M_.param_names_long, 'lambda2');
M_.param_names = char(M_.param_names, 'lambda3');
M_.param_names_tex = char(M_.param_names_tex, 'lambda3');
M_.param_names_long = char(M_.param_names_long, 'lambda3');
M_.param_names = char(M_.param_names, 'lambda4');
M_.param_names_tex = char(M_.param_names_tex, 'lambda4');
M_.param_names_long = char(M_.param_names_long, 'lambda4');
M_.param_names = char(M_.param_names, 'lambda5');
M_.param_names_tex = char(M_.param_names_tex, 'lambda5');
M_.param_names_long = char(M_.param_names_long, 'lambda5');
M_.param_names = char(M_.param_names, 'lambda6');
M_.param_names_tex = char(M_.param_names_tex, 'lambda6');
M_.param_names_long = char(M_.param_names_long, 'lambda6');
M_.param_names = char(M_.param_names, 'yo');
M_.param_names_tex = char(M_.param_names_tex, 'yo');
M_.param_names_long = char(M_.param_names_long, 'yo');
M_.param_names = char(M_.param_names, 'ho');
M_.param_names_tex = char(M_.param_names_tex, 'ho');
M_.param_names_long = char(M_.param_names_long, 'ho');
M_.param_names = char(M_.param_names, 'fo');
M_.param_names_tex = char(M_.param_names_tex, 'fo');
M_.param_names_long = char(M_.param_names_long, 'fo');
M_.param_names = char(M_.param_names, 'ro');
M_.param_names_tex = char(M_.param_names_tex, 'ro');
M_.param_names_long = char(M_.param_names_long, 'ro');
M_.param_names = char(M_.param_names, 'To');
M_.param_names_tex = char(M_.param_names_tex, 'To');
M_.param_names_long = char(M_.param_names_long, 'To');
M_.param_names = char(M_.param_names, 'do');
M_.param_names_tex = char(M_.param_names_tex, 'do');
M_.param_names_long = char(M_.param_names_long, 'do');
M_.param_names = char(M_.param_names, 'bo');
M_.param_names_tex = char(M_.param_names_tex, 'bo');
M_.param_names_long = char(M_.param_names_long, 'bo');
M_.param_names = char(M_.param_names, 'P_zo');
M_.param_names_tex = char(M_.param_names_tex, 'P\_zo');
M_.param_names_long = char(M_.param_names_long, 'P_zo');
M_.param_names = char(M_.param_names, 'r_dco');
M_.param_names_tex = char(M_.param_names_tex, 'r\_dco');
M_.param_names_long = char(M_.param_names_long, 'r_dco');
M_.param_names = char(M_.param_names, 'dco');
M_.param_names_tex = char(M_.param_names_tex, 'dco');
M_.param_names_long = char(M_.param_names_long, 'dco');
M_.param_names = char(M_.param_names, 'eo');
M_.param_names_tex = char(M_.param_names_tex, 'eo');
M_.param_names_long = char(M_.param_names_long, 'eo');
M_.param_names = char(M_.param_names, 'eho');
M_.param_names_tex = char(M_.param_names_tex, 'eho');
M_.param_names_long = char(M_.param_names_long, 'eho');
M_.param_names = char(M_.param_names, 'grantso');
M_.param_names_tex = char(M_.param_names_tex, 'grantso');
M_.param_names_long = char(M_.param_names_long, 'grantso');
M_.param_names = char(M_.param_names, 'oilro');
M_.param_names_tex = char(M_.param_names_tex, 'oilro');
M_.param_names_long = char(M_.param_names_long, 'oilro');
M_.param_names = char(M_.param_names, 'remito');
M_.param_names_tex = char(M_.param_names_tex, 'remito');
M_.param_names_long = char(M_.param_names_long, 'remito');
M_.param_names = char(M_.param_names, 'q_xo');
M_.param_names_tex = char(M_.param_names_tex, 'q\_xo');
M_.param_names_long = char(M_.param_names_long, 'q_xo');
M_.param_names = char(M_.param_names, 'q_no');
M_.param_names_tex = char(M_.param_names_tex, 'q\_no');
M_.param_names_long = char(M_.param_names_long, 'q_no');
M_.param_names = char(M_.param_names, 'bstaro');
M_.param_names_tex = char(M_.param_names_tex, 'bstaro');
M_.param_names_long = char(M_.param_names_long, 'bstaro');
M_.param_names = char(M_.param_names, 'upsilon');
M_.param_names_tex = char(M_.param_names_tex, 'upsilon');
M_.param_names_long = char(M_.param_names_long, 'upsilon');
M_.param_names = char(M_.param_names, 'Lo');
M_.param_names_tex = char(M_.param_names_tex, 'Lo');
M_.param_names_long = char(M_.param_names_long, 'Lo');
M_.param_names = char(M_.param_names, 'hlo');
M_.param_names_tex = char(M_.param_names_tex, 'hlo');
M_.param_names_long = char(M_.param_names_long, 'hlo');
M_.param_names = char(M_.param_names, 'wo');
M_.param_names_tex = char(M_.param_names_tex, 'wo');
M_.param_names_long = char(M_.param_names_long, 'wo');
M_.param_names = char(M_.param_names, 'a_za');
M_.param_names_tex = char(M_.param_names_tex, 'a\_za');
M_.param_names_long = char(M_.param_names_long, 'a_za');
M_.param_names = char(M_.param_names, 'b_x');
M_.param_names_tex = char(M_.param_names_tex, 'b\_x');
M_.param_names_long = char(M_.param_names_long, 'b_x');
M_.param_names = char(M_.param_names, 'b_n');
M_.param_names_tex = char(M_.param_names_tex, 'b\_n');
M_.param_names_long = char(M_.param_names_long, 'b_n');
M_.param_names = char(M_.param_names, 'R_zio');
M_.param_names_tex = char(M_.param_names_tex, 'R\_zio');
M_.param_names_long = char(M_.param_names_long, 'R_zio');
M_.param_names = char(M_.param_names, 'R_zao');
M_.param_names_tex = char(M_.param_names_tex, 'R\_zao');
M_.param_names_long = char(M_.param_names_long, 'R_zao');
M_.param_names = char(M_.param_names, 'zio');
M_.param_names_tex = char(M_.param_names_tex, 'zio');
M_.param_names_long = char(M_.param_names_long, 'zio');
M_.param_names = char(M_.param_names, 'zao');
M_.param_names_tex = char(M_.param_names_tex, 'zao');
M_.param_names_long = char(M_.param_names_long, 'zao');
M_.param_names = char(M_.param_names, 'zieo');
M_.param_names_tex = char(M_.param_names_tex, 'zieo');
M_.param_names_long = char(M_.param_names_long, 'zieo');
M_.param_names = char(M_.param_names, 'zaeo');
M_.param_names_tex = char(M_.param_names_tex, 'zaeo');
M_.param_names_long = char(M_.param_names_long, 'zaeo');
M_.param_names = char(M_.param_names, 'Savo');
M_.param_names_tex = char(M_.param_names_tex, 'Savo');
M_.param_names_long = char(M_.param_names_long, 'Savo');
M_.param_names = char(M_.param_names, 'ppi_nd_x');
M_.param_names_tex = char(M_.param_names_tex, 'ppi\_nd\_x');
M_.param_names_long = char(M_.param_names_long, 'ppi_nd_x');
M_.param_names = char(M_.param_names, 'ppi_nd_n');
M_.param_names_tex = char(M_.param_names_tex, 'ppi\_nd\_n');
M_.param_names_long = char(M_.param_names_long, 'ppi_nd_n');
M_.param_names = char(M_.param_names, 'pnu_nd');
M_.param_names_tex = char(M_.param_names_tex, 'pnu\_nd');
M_.param_names_long = char(M_.param_names_long, 'pnu_nd');
M_.param_names = char(M_.param_names, 'pvarpi_z');
M_.param_names_tex = char(M_.param_names_tex, 'pvarpi\_z');
M_.param_names_long = char(M_.param_names_long, 'pvarpi_z');
M_.param_names = char(M_.param_names, 'pvarpi_kx');
M_.param_names_tex = char(M_.param_names_tex, 'pvarpi\_kx');
M_.param_names_long = char(M_.param_names_long, 'pvarpi_kx');
M_.param_names = char(M_.param_names, 'pvarpi_kn');
M_.param_names_tex = char(M_.param_names_tex, 'pvarpi\_kn');
M_.param_names_long = char(M_.param_names_long, 'pvarpi_kn');
M_.param_names = char(M_.param_names, 'b_nx');
M_.param_names_tex = char(M_.param_names_tex, 'b\_nx');
M_.param_names_long = char(M_.param_names_long, 'b_nx');
M_.param_names = char(M_.param_names, 'prho_z');
M_.param_names_tex = char(M_.param_names_tex, 'prho\_z');
M_.param_names_long = char(M_.param_names_long, 'prho_z');
M_.param_names = char(M_.param_names, 'pxi_z');
M_.param_names_tex = char(M_.param_names_tex, 'pxi\_z');
M_.param_names_long = char(M_.param_names_long, 'pxi_z');
M_.param_names = char(M_.param_names, 'pgamma_s');
M_.param_names_tex = char(M_.param_names_tex, 'pgamma\_s');
M_.param_names_long = char(M_.param_names_long, 'pgamma_s');
M_.param_names = char(M_.param_names, 'pgamma_ax');
M_.param_names_tex = char(M_.param_names_tex, 'pgamma\_ax');
M_.param_names_long = char(M_.param_names_long, 'pgamma_ax');
M_.param_names = char(M_.param_names, 'pgamma_an');
M_.param_names_tex = char(M_.param_names_tex, 'pgamma\_an');
M_.param_names_long = char(M_.param_names_long, 'pgamma_an');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 58;
M_.endo_nbr = 60;
M_.param_nbr = 101;
M_.orig_endo_nbr = 60;
M_.aux_vars = [];
M_.Sigma_e = zeros(58, 58);
M_.Correlation_matrix = eye(58, 58);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('mergedModel2_static');
erase_compiled_function('mergedModel2_dynamic');
M_.orig_eq_nbr = 60;
M_.eq_nbr = 60;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 21 0;
 2 22 0;
 0 23 0;
 0 24 0;
 3 25 0;
 4 26 0;
 0 27 0;
 0 28 0;
 0 29 0;
 0 30 0;
 0 31 81;
 0 32 82;
 0 33 83;
 0 34 84;
 0 35 0;
 0 36 85;
 0 37 0;
 0 38 0;
 0 39 86;
 5 40 87;
 6 41 0;
 7 42 0;
 0 43 0;
 8 44 0;
 9 45 0;
 10 46 0;
 11 47 0;
 12 48 0;
 0 49 0;
 0 50 88;
 0 51 0;
 13 52 0;
 0 53 0;
 14 54 0;
 15 55 0;
 0 56 0;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 16 67 0;
 17 68 0;
 18 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 19 75 0;
 20 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;]';
M_.nstatic = 33;
M_.nfwrd   = 7;
M_.npred   = 19;
M_.nboth   = 1;
M_.nsfwrd   = 8;
M_.nspred   = 20;
M_.ndynamic   = 27;
M_.equations_tags = {
  3 , 'name' , 'Output - Tradable' ;
  4 , 'name' , 'Output - Nontradable' ;
  5 , 'name' , 'Public Capital' ;
  6 , 'name' , 'TFP - Tradable' ;
  7 , 'name' , 'TFP - Nontradable' ;
  8 , 'name' , 'Prices - private capital' ;
  9 , 'name' , 'Prices - public capital' ;
  10 , 'name' , 'CPI' ;
  11 , 'name' , 'FOC' ;
  15 , 'name' , 'Private capital-Tradable' ;
  16 , 'name' , 'LoM - private capital-Nontradable' ;
  17 , 'name' , 'Public standard capital' ;
  18 , 'name' , 'Standard effective capital' ;
  19 , 'name' , 'Public investment efficiency' ;
  20 , 'name' , 'LoM - public adaptation capital' ;
  21 , 'name' , 'Adaptation effective capital' ;
  22 , 'name' , 'w' ;
  24 , 'name' , 'r' ;
  26 , 'name' , 'MCC' ;
  27 , 'name' , 'Total Labor' ;
  28 , 'name' , 'FOC-Labor' ;
  29 , 'name' , 'Labor-Nonsavers' ;
  30 , 'name' , 'Market Clearing' ;
  31 , 'name' , 'Budget Constraint Nonsavers' ;
  32 , 'name' , 'Return on Infrastructure' ;
  33 , 'name' , 'Return on Standard Infrastructure' ;
  34 , 'name' , 'Return on Adaptation Infrastructure' ;
  35 , 'name' , 'r_dc' ;
  36 , 'name' , 'r*' ;
  37 , 'name' , 'Nominal GDP' ;
  38 , 'name' , 'Growth plot' ;
  39 , 'name' , 'DD' ;
  40 , 'name' , 'GAP' ;
  41 , 'name' , 'VAT' ;
  42 , 'name' , 'PT' ;
  43 , 'name' , 'Transfers' ;
  44 , 'name' , 'Concessional borrowing' ;
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:58];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(60, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(58, 1);
M_.params = NaN(101, 1);
M_.NNZDerivatives = [354; 0; -1];
load dsa_params.mat;          
for i=1:length(M_.params)
deep_parameter_name = M_.param_names(i,:);
eval(['M_.params(i)  = ' deep_parameter_name ' ;'])
end   
load steady_state_values.mat;
options_.simul.maxit = itermax;
%
% INITVAL instructions
%
options_.initval_file = 0;
oo_.steady_state( 21 ) = T_ini;
oo_.steady_state( 1 ) = q_x_ini;
oo_.steady_state( 2 ) = q_n_ini;
oo_.steady_state( 5 ) = k_x_ini;
oo_.steady_state( 6 ) = k_n_ini;
oo_.steady_state( 7 ) = L_x_ini;
oo_.steady_state( 8 ) = L_n_ini;
oo_.steady_state( 9 ) = L_ini;
oo_.steady_state( 10 ) = Lh_ini;
oo_.steady_state( 16 ) = P_k_ini;
oo_.steady_state( 17 ) = P_z_ini;
oo_.steady_state( 30 ) = e_ini;
oo_.steady_state( 31 ) = eh_ini;
oo_.steady_state( 15 ) = w_ini;
oo_.steady_state( 18 ) = P_n_ini;
oo_.steady_state( 19 ) = P_ini;
oo_.steady_state( 11 ) = i_x_ini;
oo_.steady_state( 12 ) = i_n_ini;
oo_.steady_state( 20 ) = h_ini;
oo_.steady_state( 13 ) = r_x_ini;
oo_.steady_state( 14 ) = r_n_ini;
oo_.steady_state( 32 ) = r_ini;
oo_.steady_state( 24 ) = bstar_ini;
oo_.steady_state( 25 ) = M_.params(64);
oo_.steady_state( 27 ) = M_.params(63);
oo_.steady_state( 26 ) = M_.params(67);
oo_.steady_state( 28 ) = M_.params(63);
oo_.steady_state( 37 ) = M_.params(72);
oo_.steady_state( 36 ) = M_.params(70);
oo_.steady_state( 38 ) = M_.params(71);
oo_.steady_state( 3 ) = M_.params(58);
oo_.steady_state( 4 ) = M_.params(33);
oo_.steady_state( 29 ) = 0;
oo_.steady_state( 35 ) = M_.params(40)+M_.params(43);
oo_.steady_state( 34 ) = oo_.steady_state(35)+M_.params(41);
oo_.steady_state( 42 ) = 1;
oo_.steady_state( 43 ) = 1;
oo_.steady_state( 44 ) = 1;
oo_.steady_state( 41 ) = P_n_ini/oo_.steady_state(42);
oo_.steady_state( 39 ) = oo_.steady_state(42)/oo_.steady_state(43);
oo_.steady_state( 40 ) = oo_.steady_state(42)/oo_.steady_state(44);
oo_.steady_state( 33 ) = 0;
oo_.steady_state( 23 ) = 0;
oo_.exo_steady_state( 32 ) = M_.params(67);
oo_.steady_state( 45 ) = a_x_ini;
oo_.steady_state( 46 ) = a_n_ini;
oo_.steady_state( 47 ) = zi_ini;
oo_.steady_state( 48 ) = zie_ini;
oo_.steady_state( 49 ) = za_ini;
oo_.steady_state( 50 ) = zae_ini;
oo_.steady_state( 51 ) = i_zi_ini;
oo_.steady_state( 52 ) = i_za_ini;
oo_.steady_state( 53 ) = R_zi_ini;
oo_.steady_state( 54 ) = R_za_ini;
oo_.steady_state( 55 ) = Sav_ini;
oo_.steady_state( 56 ) = zte_ini;
oo_.steady_state( 57 ) = Rzt_ini;
oo_.steady_state( 58 ) = s_ini;
oo_.steady_state( 22 ) = hl_ini;
oo_.steady_state( 59 ) = oo_.steady_state(1)+oo_.steady_state(2);
oo_.steady_state( 60 ) = 0;
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
steady;
resid(1)
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',1,'multiplicative',0,'periods',1:50,'value',1) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',2,'multiplicative',0,'periods',1:50,'value',dconc_temp) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',3,'multiplicative',0,'periods',1:250,'value',dconc_perm) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',6,'multiplicative',0,'periods',1:50,'value',gr_temp) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',7,'multiplicative',0,'periods',1:250,'value',gr_perm) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',13,'multiplicative',0,'periods',1:50,'value',oilr_temp) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',14,'multiplicative',0,'periods',1:250,'value',oilr_perm) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',17,'multiplicative',0,'periods',1:500,'value',hbar_sh) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',18,'multiplicative',0,'periods',1:500,'value',hlbar_sh) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',20,'multiplicative',0,'periods',1:50,'value',px_temp) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',21,'multiplicative',0,'periods',1:250,'value',px_perm) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',24,'multiplicative',0,'periods',1:50,'value',pm_temp) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',25,'multiplicative',0,'periods',1:250,'value',pm_perm) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',28,'multiplicative',0,'periods',1:50,'value',pmm_temp) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',29,'multiplicative',0,'periods',1:250,'value',pmm_perm) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',35,'multiplicative',0,'periods',1:50,'value',kx_nd) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',36,'multiplicative',0,'periods',1:50,'value',kn_nd) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',37,'multiplicative',0,'periods',1:50,'value',z_nd) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',38,'multiplicative',0,'periods',1:50,'value',gr_izi_nd) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',39,'multiplicative',0,'periods',1:50,'value',gr_iza_nd) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',40,'multiplicative',0,'periods',1:50,'value',izi_temp) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',41,'multiplicative',0,'periods',1:250,'value',izi_perm) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',44,'multiplicative',0,'periods',1:50,'value',iza_temp) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',45,'multiplicative',0,'periods',1:250,'value',iza_perm) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',48,'multiplicative',0,'periods',1:50,'value',rextg_nd_shock) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',49,'multiplicative',0,'periods',1:50,'value',sav_temp) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',50,'multiplicative',0,'periods',1:50,'value',izi_reconst) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',51,'multiplicative',0,'periods',1:50,'value',yn_nd) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',52,'multiplicative',0,'periods',1:50,'value',yx_nd) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',53,'multiplicative',0,'periods',2:7,'value',time_line3) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',54,'multiplicative',0,'periods',1:50,'value',s_nd_reconstdev) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',55,'multiplicative',0,'periods',1:50,'value',ax_nd_dev) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',56,'multiplicative',0,'periods',1:50,'value',an_nd_dev) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',57,'multiplicative',0,'periods',1:30,'value',y_target_shock) ];
M_.det_shocks = [ M_.det_shocks;
struct('exo_det',0,'exo_id',58,'multiplicative',0,'periods',1:50,'value',0) ];
M_.exo_det_length = 0;
options_.periods = 1000;
options_.stack_solve_algo = 6;
perfect_foresight_setup;
perfect_foresight_solver;
save('mergedModel2_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('mergedModel2_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('mergedModel2_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('mergedModel2_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('mergedModel2_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('mergedModel2_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('mergedModel2_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
